name: Continuos PR Deployment
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: echo "${{toJson(github)}}"
      - name: Check out branch
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node-modules
        run: yarn install --frozen-lockfile
      - name: Use shared Nx Cache
        id: cache-nx
        uses: actions/cache@v3
        env:
          CACHE_NAME: cache-nx
        with:
          path: ./node_modules/.cache/nx
          key: ${{ runner.os }}-build-nx-${{ hashFiles('yarn.lock') }}-${{github.event.number}}-${{ hashFiles('node_modules/.cache/nx/nxdeps.json') }}
          restore-keys: |
            ${{ runner.os }}-build-nx-${{ hashFiles('yarn.lock') }}-${{github.event.number}}
            ${{ runner.os }}-build-nx-${{ hashFiles('yarn.lock') }}
      - name: build
        run: yarn build
