name: Continuos PR Deployment
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      # - name: Show context
      #   run: |
      #     echo "${{github.sha}}"
      #     echo "${{github.run_id}}"
      #     echo "${{toJson(github)}}"
      - name: Check out branch
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check changed files
        id: no-docs-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.*
          files_ignore: docs/** # Alternatively using: `docs`
      - name: Run
        run: |
          echo "Changes: ${{ steps.changed-files-excluded.outputs.any_changed == 'true' }}"
