name: Continuos Deployment
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo "${{github.sha}}"
          echo "${{github.run_id}}"
          echo "${{toJson(github)}}"
      - name: Check out branch
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node-modules
        run: yarn install --frozen-lockfile
      - name: Use shared Nx Cache
        id: cache-nx
        uses: actions/cache@v3
        env:
          CACHE_NAME: cache-nx
        with:
          path: ./node_modules/.cache/nx
          key: ${{ runner.os }}-build-cache-${{ hashFiles('yarn.lock') }}-${{github.run_id}}
          restore-keys: |
            ${{ runner.os }}-build-cache-${{ hashFiles('yarn.lock') }}
      - name: build
        run: yarn build
