name: Continuos Deployment
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node-modules
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish demos
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist/test-pr-pipeline --dotfiles -e dev
        env:
          GITHUB_TOKEN: ${{ github.token }}
      # - name: Create GitHub deployment
      #   run: |
      #     gh api \
      #       --method POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       /repos/iankodj/${GITHUB_REPOSITORY}/deployments \
      #       -f ref
      #       -f ref='staging' \
      #       -f payload='{ "deploy": "migrate" }' \
      #       -f description='Deployed staging environment.'
      - name: Cleanup
        run: git clean -xdf
