name: '[manual] Delete PR staging'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch:'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Environment
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{github.repository}}/environments/PR-${{github.event.number}}
        env:
          GH_TOKEN: ${{ github.token }}
