name: 'TEST'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches
          cache: 'yarn'
      - name: Install node-modules
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
