name: '[manual] Delete PR staging'

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: 'Deploynment:'
        required: true
      ref:
        description: 'Ref:'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete Environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ github.token }}
          environment: ${{github.event.inputs.deployment}}
          ref: ${{github.event.inputs.ref}}
          onlyRemoveDeployments: true
